import type { IconType } from 'react-icons'
import {
  MdMenu,
  MdClose,
  MdSearch,
  MdHome,
  MdSettings,
  MdFavorite,
  MdFavoriteBorder,
  MdAdd,
  MdRemove,
  MdEdit,
  MdDelete,
  MdCheck,
  MdArrowBack,
  MdArrowForward,
  MdArrowUpward,
  MdArrowDownward,
  MdChevronLeft,
  MdChevronRight,
  MdExpandMore,
  MdExpandLess,
  MdMoreVert,
  MdMoreHoriz,
  MdInfo,
  MdWarning,
  MdError,
  MdCheckCircle,
  MdCancel,
  MdPerson,
  MdAccountCircle,
  MdNotifications,
  MdMail,
  MdShare,
  MdVisibility,
  MdVisibilityOff,
  MdStar,
  MdStarBorder,
  MdThumbUp,
  MdThumbDown,
  MdRefresh,
  MdDownload,
  MdUpload,
  MdFilterList,
  MdSort,
  MdCalendarToday,
  MdSchedule,
  MdLocationOn,
  MdPhone,
  MdCameraAlt,
  MdImage,
  MdAttachFile,
  MdMic,
  MdSend,
  MdLock,
  MdLockOpen,
} from 'react-icons/md'
import type { IconName } from '../../types/components'

export const iconMap: Record<IconName, IconType> = {
  menu: MdMenu,
  close: MdClose,
  search: MdSearch,
  home: MdHome,
  settings: MdSettings,
  favorite: MdFavorite,
  'favorite-border': MdFavoriteBorder,
  add: MdAdd,
  remove: MdRemove,
  edit: MdEdit,
  delete: MdDelete,
  check: MdCheck,
  'arrow-back': MdArrowBack,
  'arrow-forward': MdArrowForward,
  'arrow-up': MdArrowUpward,
  'arrow-down': MdArrowDownward,
  'chevron-left': MdChevronLeft,
  'chevron-right': MdChevronRight,
  'expand-more': MdExpandMore,
  'expand-less': MdExpandLess,
  'more-vert': MdMoreVert,
  'more-horiz': MdMoreHoriz,
  info: MdInfo,
  warning: MdWarning,
  error: MdError,
  'check-circle': MdCheckCircle,
  cancel: MdCancel,
  person: MdPerson,
  'account-circle': MdAccountCircle,
  notifications: MdNotifications,
  mail: MdMail,
  share: MdShare,
  visibility: MdVisibility,
  'visibility-off': MdVisibilityOff,
  star: MdStar,
  'star-border': MdStarBorder,
  'thumb-up': MdThumbUp,
  'thumb-down': MdThumbDown,
  refresh: MdRefresh,
  download: MdDownload,
  upload: MdUpload,
  'filter-list': MdFilterList,
  sort: MdSort,
  calendar: MdCalendarToday,
  schedule: MdSchedule,
  location: MdLocationOn,
  phone: MdPhone,
  camera: MdCameraAlt,
  image: MdImage,
  'attach-file': MdAttachFile,
  mic: MdMic,
  send: MdSend,
  lock: MdLock,
  'lock-open': MdLockOpen,
}
